import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import okhttp3.*;
import javax.net.ssl.HostnameVerifier;
import javax.net.ssl.SSLContext;
import javax.net.ssl.SSLSession;
import javax.net.ssl.TrustManager;
import javax.net.ssl.X509TrustManager;
import java.security.SecureRandom;
import java.security.cert.X509Certificate;
import java.net.InetSocketAddress;
import java.net.Proxy;
import javax.net.ssl.SSLContext;
import javax.net.ssl.TrustManager;
import javax.net.ssl.X509TrustManager;
import java.security.SecureRandom;
import java.security.cert.X509Certificate;
import org.openqa.selenium.support.ui.WebDriverWait;
import java.time.Duration;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.interactions.Actions;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import io.testgrid.listeners.TestListener;
import io.testgrid.listeners.RetryFailedTestCases;
import io.testgrid.tg;
import org.testng.annotations.*;
import app.getxray.xray.testng.annotations.XrayTest;
import io.testgrid.enums.ComparisonType;
import org.json.JSONObject;
import io.testgrid.enums.Direction;
import io.testgrid.enums.Size;
import io.testgrid.enums.Buttons;
import static io.testgrid.baseClass.driver;
import org.openqa.selenium.*;
import static io.testgrid.enums.KeyboardKeys.*;
import org.openqa.selenium.support.ui.Select;
import java.net.*;
import java.util.*;
import java.io.*;
import java.util.concurrent.TimeUnit;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.testng.annotations.Test;

class fndigitalwebfibersignupqlab03 {

	public static void fndigitalwebfibersignupqlab03() {
		tg.navigateToUrl("https://qlab03.fiber.t-mobile.com/");
		tg.wait("ele_digitalWebLinkMyAccount", ComparisonType.IS_CLICKABLE, 20);
		tg.click("ele_digitalWebLinkMyAccount", 1);
		tg.wait("ele_digitalWebLinkSignIn", ComparisonType.IS_CLICKABLE);
		tg.click("ele_digitalWebLinkSignIn", 1);
		tg.wait("ele_digitalWebLinkSignUp", ComparisonType.IS_CLICKABLE, 20);
		tg.click("ele_digitalWebLinkSignUp", 1);
		tg.wait("ele_digitalWebSignUpTextBoxFName", ComparisonType.IS_CLICKABLE, 20);
		tg.type("ele_digitalWebSignUpTextBoxFName", var_firstName);
		tg.click("ele_digitalWebSignUpTextBoxLName", 1);
		tg.type("ele_digitalWebSignUpTextBoxLName", var_lastName);
		tg.click("ele_digitalWebTextBoxSignUpEmail", 1);
		tg.type("ele_digitalWebTextBoxSignUpEmail", var_emailId);
		tg.wait("ele_digitalWebSignUpTextBoxPassword", ComparisonType.IS_CLICKABLE);
		tg.click("ele_digitalWebSignUpTextBoxPassword", 1);
		tg.type("ele_digitalWebSignUpTextBoxPassword", "pass@123");
		tg.wait("ele_digitalWebBtnContinueSignUp", ComparisonType.IS_CLICKABLE);
		tg.click("ele_digitalWebBtnContinueSignUp", 1);
		tg.wait("ele_digitalWebTextBoxEmailOtpLetsConfirmItsYou", ComparisonType.IS_CLICKABLE, 15);
		tg.click("ele_digitalWebTextBoxEmailOtpLetsConfirmItsYou", 1);
		tg_String var_emailOTP = "";
		tg.testFunction("fnDigitalWebFiberCvsPinGenerationQlab03");
		var_emailOTP = tg.saveToVariable(var_cvsPin, var_emailOTP);
		tg.printLogs(var_emailOTP);
		tg.type("ele_digitalWebTextBoxEmailOtpLetsConfirmItsYou", var_cvsPin);
		tg.wait("ele_digitalWebBtnContinueLetsConfirmItsYou", ComparisonType.IS_CLICKABLE);
		tg.click("ele_digitalWebBtnContinueLetsConfirmItsYou", 1);
	}
}