import org.openqa.selenium.*;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.support.ui.ExpectedConditions;
import static io.testgrid.baseClass.driver;
import java.time.format.DateTimeFormatter;
import java.time.LocalDateTime;
import java.util.regex.*;
import java.util.Random;
import java.time.LocalDate;
import org.json.JSONArray;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import java.net.HttpURLConnection;
import java.net.URL;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import okhttp3.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.net.ssl.HostnameVerifier;
import javax.net.ssl.SSLContext;
import javax.net.ssl.SSLSession;
import javax.net.ssl.TrustManager;
import javax.net.ssl.X509TrustManager;
import java.security.SecureRandom;
import java.security.cert.X509Certificate;
import java.net.InetSocketAddress;
import java.net.Proxy;
import javax.net.ssl.SSLContext;
import javax.net.ssl.TrustManager;
import javax.net.ssl.X509TrustManager;
import java.security.SecureRandom;
import java.security.cert.X509Certificate;
import org.openqa.selenium.support.ui.WebDriverWait;
import java.time.Duration;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.interactions.Actions;
import java.text.SimpleDateFormat;
import java.util.Locale;
import java.util.Date;
import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.SearchContext;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.support.ui.ExpectedConditions;
import java.time.Duration;
import io.testgrid.listeners.TestListener;
import io.testgrid.listeners.RetryFailedTestCases;
import io.testgrid.tg;
import org.testng.annotations.*;
import app.getxray.xray.testng.annotations.XrayTest;
import io.testgrid.enums.ComparisonType;
import org.json.JSONObject;
import io.testgrid.enums.Direction;
import io.testgrid.enums.Size;
import io.testgrid.enums.Buttons;
import static io.testgrid.baseClass.driver;
import org.openqa.selenium.*;
import static io.testgrid.enums.KeyboardKeys.*;
import org.openqa.selenium.support.ui.Select;
import java.net.*;
import java.util.*;
import java.io.*;
import java.util.concurrent.TimeUnit;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.testng.annotations.Test;

@Listeners(TestListener.class);
public class digital_mytmo_myaccountdashboard_manageautopay_updatecarddetails {

	@Test(retryAnalyzer = RetryFailedTestCases.class)
	public void digital_mytmo_myaccountdashboard_manageautopay_updatecarddetails() {
		tg.openBrowser();
		tg.navigateToUrl("https://digital-qlab02.t-mobile.com");
		// [DISABLED] if(tg.performAssert(var_env, ComparisonType.EQUAL_TO, "Qlab02")){
		// [DISABLED] START_CUSTOM_SCRIPT;
		// [DISABLED] START_CUSTOM_SCRIPT;
		// [DISABLED] driver.get(var_qlab02MyTMOURL);
		// [DISABLED] END_CUSTOM_SCRIPT;
		// [DISABLED] END_CUSTOM_SCRIPT;
		// [DISABLED] } else {
		// [DISABLED] if(tg.performAssert(var_env, ComparisonType.EQUAL_TO, "Qlab03")){
		// [DISABLED] START_CUSTOM_SCRIPT;
		// [DISABLED] START_CUSTOM_SCRIPT;
		// [DISABLED] driver.get(var_qlab03MyTMOURL);
		// [DISABLED] END_CUSTOM_SCRIPT;
		// [DISABLED] }
		// [DISABLED] }
		// [DISABLED] END_CUSTOM_SCRIPT;
		var_cardUserFirstName = tg.saveToVariable("GIRRI", var_cardUserFirstName);
		var_username = tg.saveToVariable("3322500986@testtdm.com", var_username);
		var_password = tg.saveToVariable("pass@123", var_password);
		var_emailId = tg.saveToVariable("3322500986@testtdm.com", var_emailId);
		// [DISABLED] START_CUSTOM_SCRIPT;
		// [DISABLED] START_CUSTOM_SCRIPT;
		// [DISABLED] driver.get(var_qlab02MyTMOURL);
		// [DISABLED] END_CUSTOM_SCRIPT;
		// [DISABLED] END_CUSTOM_SCRIPT;
		tg.wait("ele_digitalMyTMOListMyaccount", ComparisonType.IS_VISIBLE);
		tg.click("ele_digitalMyTMOListMyaccount", 1);
		tg.wait("ele_digitalMyTMOLinkMyAccountLogin", ComparisonType.IS_VISIBLE);
		tg.click("ele_digitalMyTMOLinkMyAccountLogin", 1);
		tg.testFunction("fnDigitalWebMyTMOLogin");
		// [DISABLED] tg.wait("ele_digitalMyTMOTextLoginEmailorPhone", ComparisonType.IS_VISIBLE);
		// [DISABLED] tg.click("ele_digitalMyTMOTextLoginEmailorPhone", 1);
		// [DISABLED] tg.wait("ele_digitalMyTMOTextLoginEmailorPhone", ComparisonType.IS_VISIBLE);
		// [DISABLED] tg.type("ele_digitalMyTMOTextLoginEmailorPhone", "MJBSHBEDA09289898@GMAIL.COM");
		// [DISABLED] var_updateCardloginUserName = tg.saveToVariable("MJBSHBEDA09289898@GMAIL.COM", var_updateCardloginUserName);
		// [DISABLED] tg.type("ele_digitalMyTMOTextLoginEmailorPhone", var_updateCardloginUserName);
		// [DISABLED] tg.wait("ele_digitalMyTMOBtnLoginNext", ComparisonType.IS_VISIBLE);
		// [DISABLED] tg.click("ele_digitalMyTMOBtnLoginNext", 1);
		// [DISABLED] tg.wait("ele_digitalMyTMOTextLoginPassword", ComparisonType.IS_VISIBLE);
		// [DISABLED] tg.click("ele_digitalMyTMOTextLoginPassword", 1);
		// [DISABLED] tg.wait("ele_digitalMyTMOTextLoginPassword", ComparisonType.IS_VISIBLE);
		// [DISABLED] var_updateCardloginUserPwd = tg.saveToVariable("pass@123", var_updateCardloginUserPwd);
		// [DISABLED] tg.typeEncrypted("ele_digitalMyTMOTextLoginPassword", "Tul5JS6B3oEBl/Ix8pFjVQ==:MTIzNDU2Nzg5MTAxMTEyMQ==");
		// [DISABLED] tg.type("ele_digitalMyTMOTextLoginPassword", var_updateCardloginUserPwd);
		// [DISABLED] tg.wait("ele_digitalMyTMOBtnLoginLogin", ComparisonType.IS_VISIBLE);
		// [DISABLED] tg.click("ele_digitalMyTMOBtnLoginLogin", 1);
		// [DISABLED] tg.wait("ele_digitalMyTMOBtnLoginBeforeVerificationCodeContinue", ComparisonType.IS_VISIBLE);
		// [DISABLED] tg.click("ele_digitalMyTMOBtnLoginBeforeVerificationCodeContinue", 1);
		// [DISABLED] var_username = tg.saveToVariable(var_updateCardloginUserName, var_username);
		// [DISABLED] tg.printLogs(var_username);
		// [DISABLED] var_updateCardNumber = tg.saveToVariable("4642340000000006", var_updateCardNumber);
		tg.testFunction("fnDigitalWebMiltonApiAuthTokenGenerationQlab02");
		tg.testFunction("fnDigitalWebFiberMiltonGenerate2FAPinQlab02");
		tg.printLogs(var_mpin);
		tg_String var_emailCode = "";
		var_emailCode = tg.saveToVariable(var_mpin, var_emailCode);
		// [DISABLED] START_CUSTOM_SCRIPT;
		// [DISABLED] START_CUSTOM_SCRIPT;
		// [DISABLED] WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
		// [DISABLED] WebElement emailCodeField = wait.until(ExpectedConditions.elementToBeClickable(By.xpath("//input[@id='code']") ));
		// [DISABLED] emailCodeField.click();
		// [DISABLED] for (char c : var_emailCode.toCharArray()) {
		// [DISABLED] emailCodeField.sendKeys(String.valueOf(c));
		// [DISABLED] System.out.println(c);
		// [DISABLED] }
		// [DISABLED] END_CUSTOM_SCRIPT;
		// [DISABLED] END_CUSTOM_SCRIPT;
		if(tg.performAssert("ele_digitalMyTMOLoginVerificationCode", ComparisonType.IS_VISIBLE)){
		tg.click("ele_digitalMyTMOLoginVerificationCode");
		tg.type("ele_digitalMyTMOLoginVerificationCode", var_mpin);
		tg.wait("ele_digitalMyTMOBtnLoginPostVerificationCodeContinue", ComparisonType.IS_CLICKABLE);
		tg.click("ele_digitalMyTMOBtnLoginPostVerificationCodeContinue");
		}
		// [DISABLED] tg.wait("ele_digitalMyTMOLoginVerificationCode", ComparisonType.IS_VISIBLE, 20);
		// [DISABLED] tg.click("ele_digitalMyTMOLoginVerificationCode", 1);
		// [DISABLED] tg.wait("ele_digitalMyTMOLoginVerificationCode", ComparisonType.IS_VISIBLE);
		// [DISABLED] tg.type("ele_digitalMyTMOLoginVerificationCode", var_mpin);
		tg.wait(2);
		// [DISABLED] tg.wait("ele_digitalMyTMOBtnLoginPostVerificationCodeContinue", ComparisonType.IS_VISIBLE);
		// [DISABLED] tg.click("ele_digitalMyTMOBtnLoginPostVerificationCodeContinue", 1);
		// [DISABLED] var_cardUserFirstName = tg.saveToVariable("jhjxhdj", var_cardUserFirstName);
		tg.wait("ele_digitalMyTMOListHomeUsername", ComparisonType.IS_VISIBLE);
		tg.check.contains("ele_digitalMyTMOListHomeUsername",var_cardUserFirstName);
		tg.click("ele_digitalMyTMOListHomeUsername", 1);
		tg.wait("ele_digitalMyTMOListItemProfile", ComparisonType.IS_VISIBLE);
		tg.click("ele_digitalMyTMOListItemProfile", 1);
		tg.wait("ele_digitalMyTMOLinkBillingpreferences", ComparisonType.IS_VISIBLE);
		tg.click("ele_digitalMyTMOLinkBillingpreferences", 1);
		tg.wait("ele_digitalMyTMOListItemPaymentmethods", ComparisonType.IS_VISIBLE);
		tg.click("ele_digitalMyTMOListItemPaymentmethods", 1);
		tg.wait("ele_digitalMyTMOBtnMywalletCard", ComparisonType.IS_VISIBLE);
		tg.click("ele_digitalMyTMOBtnMywalletCard", 1);
		tg.wait("ele_digitalMyTMOTextAddacardNameonCard", ComparisonType.IS_VISIBLE);
		tg.click("ele_digitalMyTMOTextAddacardNameonCard", 1);
		tg.wait("ele_digitalMyTMOTextAddacardNameonCard", ComparisonType.IS_VISIBLE);
		// [DISABLED] var_updateCardNameoncard = tg.saveToVariable("TG Automation", var_updateCardNameoncard);
		tg.type("ele_digitalMyTMOTextAddacardNameonCard", var_updateCardNameoncard);
		tg.wait("ele_digitalMyTMOTextBoxNameoncard", ComparisonType.IS_VISIBLE);
		tg.click("ele_digitalMyTMOTextBoxNameoncard", 1);
		tg.wait("ele_digitalMyTMOTextBoxNameoncard", ComparisonType.IS_VISIBLE);
		tg.click("ele_digitalMyTMOTextBoxNameoncard", 1);
		tg.wait("ele_digitalMyTMOTextBoxCardnumber", ComparisonType.IS_VISIBLE, 20);
		tg.click("ele_digitalMyTMOTextBoxCardnumber", 1);
		START_CUSTOM_SCRIPT;
		WebElement cardNumberField = driver.findElement(By.xpath("//input[@id='field-cardNumber']"));
		for (char ch : var_updateCardNumber.toCharArray()) {
		cardNumberField.sendKeys(String.valueOf(ch));
		}
		END_CUSTOM_SCRIPT;
		// [DISABLED] tg.type("ele_digitalMyTMOTextBoxCardnumber", "4642340000000006");
		tg.wait("ele_digitalMyTMOTextAddacardExpdt", ComparisonType.IS_VISIBLE);
		tg.click("ele_digitalMyTMOTextAddacardExpdt", 1);
		tg.wait("ele_digitalMyTMOTextBoxCardExpiryDt", ComparisonType.IS_VISIBLE);
		tg.click("ele_digitalMyTMOTextBoxCardExpiryDt", 1);
		tg.wait("ele_digitalMyTMOTextBoxCardExpiryDt", ComparisonType.IS_VISIBLE);
		// [DISABLED] var_updateCardExpdt = tg.saveToVariable("02/30", var_updateCardExpdt);
		tg.type("ele_digitalMyTMOTextBoxCardExpiryDt", var_updateCardExpdt);
		tg.wait("ele_digitalMyTMOTextAddacardCVV", ComparisonType.IS_VISIBLE);
		tg.click("ele_digitalMyTMOTextAddacardCVV", 1);
		tg.wait("ele_digitalMyTMOTextBoxCVV", ComparisonType.IS_VISIBLE);
		tg.click("ele_digitalMyTMOTextBoxCVV", 1);
		tg.wait("ele_digitalMyTMOTextBoxCVV", ComparisonType.IS_VISIBLE);
		// [DISABLED] var_updateCardCVV = tg.saveToVariable("123", var_updateCardCVV);
		tg.type("ele_digitalMyTMOTextBoxCVV", var_updateCardCVV);
		tg.wait("ele_digitalMyTMOTextBoxZipCode", ComparisonType.IS_VISIBLE);
		tg.click("ele_digitalMyTMOTextBoxZipCode", 1);
		tg.wait("ele_digitalMyTMOTextBoxZipCode", ComparisonType.IS_VISIBLE);
		// [DISABLED] var_updateCardZip = tg.saveToVariable(75024, var_updateCardZip);
		tg.type("ele_digitalMyTMOTextBoxZipCode", var_updateCardZip);
		tg.wait("ele_digitalMyTMOBtnAddacardContinue", ComparisonType.IS_VISIBLE);
		tg.click("ele_digitalMyTMOBtnAddacardContinue", 1);
		tg.wait("ele_digitalMyTMOLinkAddacardBack", ComparisonType.IS_VISIBLE);
		tg.click("ele_digitalMyTMOLinkAddacardBack", 1);
		tg.wait("ele_digitalMyTMOImageWalletTMobile", ComparisonType.IS_VISIBLE);
		tg.check.isVisible("ele_digitalMyTMOImageWalletTMobile");
		tg.click("ele_digitalMyTMOImageWalletTMobile", 1);
		tg.wait("ele_digitalMyTMOListHomeUsernameBack", ComparisonType.IS_VISIBLE);
		tg.click("ele_digitalMyTMOListHomeUsernameBack", 1);
		tg.wait("ele_digitalMyTMOBtnHomeLogout", ComparisonType.IS_VISIBLE);
		tg.click("ele_digitalMyTMOBtnHomeLogout", 1);
		tg.close();
	}
}