import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import okhttp3.*;
import javax.net.ssl.HostnameVerifier;
import javax.net.ssl.SSLContext;
import javax.net.ssl.SSLSession;
import javax.net.ssl.TrustManager;
import javax.net.ssl.X509TrustManager;
import java.security.SecureRandom;
import java.security.cert.X509Certificate;
import java.net.InetSocketAddress;
import java.net.Proxy;
import javax.net.ssl.SSLContext;
import javax.net.ssl.TrustManager;
import javax.net.ssl.X509TrustManager;
import java.security.SecureRandom;
import java.security.cert.X509Certificate;
import org.openqa.selenium.support.ui.WebDriverWait;
import java.time.Duration;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.interactions.Actions;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.text.SimpleDateFormat;
import java.util.Locale;
import java.util.Date;
import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.SearchContext;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.support.ui.ExpectedConditions;
import java.time.Duration;
import io.testgrid.listeners.TestListener;
import io.testgrid.listeners.RetryFailedTestCases;
import io.testgrid.tg;
import org.testng.annotations.*;
import app.getxray.xray.testng.annotations.XrayTest;
import io.testgrid.enums.ComparisonType;
import org.json.JSONObject;
import io.testgrid.enums.Direction;
import io.testgrid.enums.Size;
import io.testgrid.enums.Buttons;
import static io.testgrid.baseClass.driver;
import org.openqa.selenium.*;
import static io.testgrid.enums.KeyboardKeys.*;
import org.openqa.selenium.support.ui.Select;
import java.net.*;
import java.util.*;
import java.io.*;
import java.util.concurrent.TimeUnit;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.testng.annotations.Test;

class fndigitalweblotusflarecancelorder {

	public static void fndigitalweblotusflarecancelorder() {
		tg.navigateToUrl("https://portal.qlab03.fiber.t-mobile.com/");
		tg.wait("ele_DigitalWebLotusFlareBtnAzureAD", ComparisonType.IS_CLICKABLE, 40);
		tg.click("ele_DigitalWebLotusFlareBtnAzureAD", 1);
		tg.testFunction("fnDigitaWebRepLogin_copy");
		tg.wait("ele_digitalWebLotusFlareDropdownCustomerCare", ComparisonType.IS_CLICKABLE, 40);
		tg.click("ele_digitalWebLotusFlareDropdownCustomerCare", 1);
		tg.wait("ele_digitalWebLotusFlareLinkUserManager", ComparisonType.IS_CLICKABLE, 20);
		tg.click("ele_digitalWebLotusFlareLinkUserManager", 1);
		// [DISABLED] tg.wait("ele_digitalWebLotusFlareDropDownAccountID", ComparisonType.IS_VISIBLE);
		tg.wait("ele_digitalMyTMOTextAddacardNameonCard", ComparisonType.IS_VISIBLE);
		tg.performDoubleClick("ele_digitalMyTMOTextAddacardNameonCard");
		tg.wait("ele_digitalWebDropdownValueSamsonMSISDN", ComparisonType.IS_VISIBLE);
		tg.click("ele_digitalWebDropdownValueSamsonMSISDN", 1);
		tg.click("ele_digitalWebLotusFlareTextBoxSamsonMSISDN", 1);
		tg.type("ele_digitalWebLotusFlareTextBoxSamsonMSISDN", var_subscriberNum);
		tg.wait("ele_DigitalWebLotusFlareBtnSearch", ComparisonType.IS_CLICKABLE);
		tg.click("ele_DigitalWebLotusFlareBtnSearch");
		tg.wait("ele_digitalWebLFBtnActivateSubscriber", ComparisonType.IS_CLICKABLE, 40);
		tg.click("ele_digitalWebLFBtnActivateSubscriber");
		tg.wait("ele_digitalWebLFBtnYesActivatesubscriber", ComparisonType.IS_CLICKABLE, 20);
		tg.click("ele_digitalWebLFBtnYesActivatesubscriber");
		tg.wait(10);
		tg.wait("ele_digitalWebLotusFlareLabelSamsonMSISDN", ComparisonType.IS_VISIBLE, 20);
		tg_String var_eleLFsamsonmsisdn = "";
		tg_String var_eleLFsamsonban = "";
		tg_String var_eleLFbillingday = "";
		var_eleLFsamsonmsisdn = tg.saveToVariable("ele_digitalWebLotusFlareLabelSamsonMSISDN", var_eleLFsamsonmsisdn);
		var_eleLFsamsonban = tg.saveToVariable("ele_digitalWebLFLabelSamsonBAN", var_eleLFsamsonban);
		var_eleLFbillingday = tg.saveToVariable("ele_digitalWebLotusFlareLabelBillingday", var_eleLFbillingday);
	}
}